import jsPDF from 'jspdf'

interface InvoicePDFData {
  invoiceNumber: string
  status: string
  clientName: string
  clientEmail: string
  dueDate: string
  total: number
  items: Array<{
    description: string
    quantity: number
    unitPrice: number
    amount: number
  }>
}

function formatCurrency(cents: number): string {
  return `$${(cents / 100).toLocaleString('en-US', { minimumFractionDigits: 2 })}`
}

export function generateInvoicePDF(data: InvoicePDFData): jsPDF {
  const doc = new jsPDF()
  const pageWidth = doc.internal.pageSize.getWidth()

  doc.setFontSize(24)
  doc.setFont('helvetica', 'bold')
  doc.text('INVOICE', 20, 30)

  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(100, 100, 100)
  doc.text(data.invoiceNumber, 20, 38)
  doc.text(`Status: ${data.status.toUpperCase()}`, 20, 44)

  doc.setTextColor(0, 0, 0)
  doc.setFontSize(10)
  doc.text(`Due: ${data.dueDate}`, pageWidth - 20, 30, { align: 'right' })

  doc.setDrawColor(200, 200, 200)
  doc.line(20, 55, pageWidth - 20, 55)

  doc.setFontSize(11)
  doc.setFont('helvetica', 'bold')
  doc.text('Bill To:', 20, 65)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)
  doc.text(data.clientName, 20, 72)
  if (data.clientEmail) {
    doc.text(data.clientEmail, 20, 78)
  }

  doc.line(20, 90, pageWidth - 20, 90)

  const startY = 100
  const colDesc = 20
  const colQty = 120
  const colPrice = 145
  const colAmount = 175

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(10)
  doc.text('Description', colDesc, startY)
  doc.text('Qty', colQty, startY, { align: 'right' })
  doc.text('Unit Price', colPrice, startY, { align: 'right' })
  doc.text('Amount', colAmount, startY, { align: 'right' })

  doc.line(20, startY + 3, pageWidth - 20, startY + 3)

  doc.setFont('helvetica', 'normal')
  let y = startY + 12

  for (const item of data.items) {
    if (y > 260) {
      doc.addPage()
      y = 30
    }
    doc.text(item.description, colDesc, y)
    doc.text(String(item.quantity), colQty, y, { align: 'right' })
    doc.text(formatCurrency(item.unitPrice), colPrice, y, { align: 'right' })
    doc.text(formatCurrency(item.amount), colAmount, y, { align: 'right' })
    y += 8
  }

  doc.line(20, y, pageWidth - 20, y)
  y += 8

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(12)
  doc.text('Total', colPrice, y, { align: 'right' })
  doc.text(formatCurrency(data.total), colAmount, y, { align: 'right' })

  doc.setFontSize(8)
  doc.setTextColor(150, 150, 150)
  doc.text('Generated by Como Time Tracker', pageWidth / 2, 285, { align: 'center' })

  return doc
}
